### PR TITLE
Fix implicit declaration of pthread

### PR DESCRIPTION
**Pull request by heitbaum**
Fixes compile with gcc-12.2

    /build/serial2mqtt/src/Log.cpp: In member function ‘void Log::log(char, const char*, uint32_t, const char*, const char*, ...)’:
    /build/serial2mqtt/src/Log.cpp:157:24: error: ‘pthread_self’ was not declared in this scope; did you mean ‘pthread_t’?
      157 |     pthread_getname_np(pthread_self(), _application, sizeof(_application));
          |                        ^~~~~~~~~~~~
          |                        pthread_t
    /build/serial2mqtt/src/Log.cpp:157:5: error: ‘pthread_getname_np’ was not declared in this scope
      157 |     pthread_getname_np(pthread_self(), _application, sizeof(_application));
          |     ^~~~~~~~~~~~~~~~~~

### CODE REVIEW

**Comment by vortex314** [comment]
accepted
